"""Add post title

Revision ID: 0cea241f5249
Revises: e43159d9fd5b
Create Date: 2022-10-27 11:30:48.029887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cea241f5249'
down_revision = 'e43159d9fd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.Text(), nullable=True))
    op.drop_column('post', 'post')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.BLOB(), nullable=True))
    op.add_column('post', sa.Column('post', sa.TEXT(), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
