"""empty message

Revision ID: 1182dfe70f92
Revises: 7f7a81c9418f
Create Date: 2022-10-27 11:30:49.235054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1182dfe70f92'
down_revision = '7f7a81c9418f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.Text(), nullable=True))
    op.drop_index('ix_post_article_published', table_name='post')
    op.drop_column('post', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post', sa.TEXT(), nullable=True))
    op.create_index('ix_post_article_published', 'post', ['article_published'], unique=False)
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
