"""Add admin functionality

Revision ID: 27aba0f4bf2d
Revises: 4a80a3aafa43
Create Date: 2022-10-26 09:26:54.918639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27aba0f4bf2d'
down_revision = '4a80a3aafa43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_column('post', 'published')
    # ### end Alembic commands ###
