"""Delete description from post

Revision ID: 4a80a3aafa43
Revises: 1dfe1c4b2332
Create Date: 2022-10-25 12:35:48.109001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a80a3aafa43'
down_revision = '1dfe1c4b2332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post', sa.Text(), nullable=True))
    op.drop_column('post', 'description')
    op.drop_column('post', 'post_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_title', sa.TEXT(), nullable=True))
    op.add_column('post', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('post', 'post')
    # ### end Alembic commands ###
