"""empty message

Revision ID: 7f7a81c9418f
Revises: e43159d9fd5b
Create Date: 2022-10-26 11:55:19.589082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7a81c9418f'
down_revision = 'e43159d9fd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('article_published', sa.DateTime(), nullable=True))
    op.drop_index('ix_post_timestamp', table_name='post')
    op.create_index(op.f('ix_post_article_published'), 'post', ['article_published'], unique=False)
    op.drop_column('post', 'timestamp')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.BLOB(), nullable=True))
    op.add_column('post', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_post_article_published'), table_name='post')
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_column('post', 'article_published')
    # ### end Alembic commands ###
