"""empty message

Revision ID: aa4b1eba36c4
Revises: 1182dfe70f92
Create Date: 2022-10-27 12:20:40.455400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4b1eba36c4'
down_revision = '1182dfe70f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'description')
    # ### end Alembic commands ###
