"""changed account created field to date type

Revision ID: b68938942e86
Revises: 9db2be83aebe
Create Date: 2022-10-25 09:09:35.502309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68938942e86'
down_revision = '9db2be83aebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_account_created', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_account_created', 'user', ['account_created'], unique=False)
    # ### end Alembic commands ###
